{{- if eq (include "service-account.isOpenShift" .) "true" -}}
{{ $namespace := .Release.Namespace }}
{{ $serviceAccount := include "service-account.name" . }}
{{ $saName := printf "system:serviceaccount:%s:%s" $namespace $serviceAccount }}
{{ $labels := include "service-account.labels" . }}
{{- if eq "privileged" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-%s-%s" $namespace $serviceAccount . }}-cr
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - {{ printf "%s-%s-%s" $namespace $serviceAccount . }}
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-%s-%s" $namespace $serviceAccount . }}-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-%s-%s" $namespace $serviceAccount . }}-cr
subjects:
  - kind: ServiceAccount
    name: {{ include "service-account.name" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}