{{ if .Values.license }}
{{ if .Values.gateway.enable }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-gateway-setupfile
  labels: {{- include "api-pod.labels" . | nindent 5 }}
data:
  Setup.cfg: |-

    servers.jvm_options="{{ .Values.gateway.setupfile.servers.jvm_options }}"
    servers.keystore_password="$GATEWAY_SERVERS_KEYSTORE_PASSWORD"
    servers.keystore_alias="{{ .Values.gateway.setupfile.servers.keystore_alias }}"
    servers.keystore_filename="{{ .Values.gateway.setupfile.servers.keystore_filename }}"
    servers.max_file_size="{{ .Values.gateway.setupfile.servers.max_file_size }}"
    servers.max_files="{{ .Values.gateway.setupfile.servers.max_files }}"
    servers.console_log_level="{{ .Values.gateway.setupfile.servers.console_log_level }}"
    servers.trace_specification="{{ .Values.gateway.setupfile.servers.trace_specification }}"

    apigateway.domainName={{ .Values.gateway.hostname }}
    apigateway.pem_servers={{ .Values.gateway.setupfile.gateway.pem_servers }}
    apigateway.pr_servers={{ .Values.gateway.setupfile.gateway.pr_servers }}
    apgateway.max_file_size={{ .Values.gateway.setupfile.gateway.max_file_size }}
    apigateway.max_request_size={{ .Values.gateway.setupfile.gateway.max_request_size }}
    apigateway.hostname_validation_required="{{.Values.gateway.setupfile.gateway.hostname_validation_required }}"

    {{- include "ibmpemstandard.dbsetup" . | nindent 5 }}
    {{- include "ibmpemstandard.seas" . | nindent 5 }}
    {{- include "ibmpemstandard.serversetup" . | nindent 5 }}

{{ end }}
{{ end }}
