{{ if .Values.license }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}.network-policy"
spec:
  podSelector:
    matchLabels:
      tier: {{ .Release.Name }}-backend
  ingress:
  - from: []
  policyTypes:
  - Ingress
{{ end }}
