{{ if .Values.license }}
{{ if .Values.communitymanager.install }}
{{ if .Values.communitymanager.nonprod.enable }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-nonprodpcm-route
  labels: {{- include "nonprodpcm-pod.labels" . | nindent 5 }}
spec:
  {{ if .Values.communitymanager.nonprod.hostname }}
  host: {{ .Values.communitymanager.nonprod.hostname }}
  {{ end }}
  to:
    kind: Service
    name: {{ .Release.Name }}-nonprodpcm-service
  port:
    targetPort: 9080
  {{ if .Values.communitymanager.nonprod.setupfile.server.ssl.enabled }}
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  {{ end }}
{{ end }}
{{ end }}
{{ end }}
