{{ if .Values.license }}
{{ if .Values.communitymanager.install }}
{{ if .Values.communitymanager.nonprod.enable }}
{{- if .Values.communitymanager.nonprod.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-nonprodpcm-hpac
  labels: {{- include "nonprodpcm-pod.labels" . | nindent 5 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-pcm-nonprod
  minReplicas: {{ .Values.communitymanager.nonprod.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.communitymanager.nonprod.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.communitymanager.nonprod.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
{{- end }}
{{ end }}
